image: python:3.12

variables:
  APP_DIR: "DEV/code_quality_toolkit"   # ← carpeta donde está tu Makefile y pyproject
  PYTEST_ADDOPTS: "-q -o junit_family=xunit2 --junitxml=reports/junit.xml --cov=. --cov-report=term --cov-report=xml:reports/coverage.xml --cov-report=html:htmlcov"

cache:
  paths:
    - .venv
    - .cache/pip

stages:
  - debug
  - lint
  - typecheck
  - unit
  - coverage
  - analyze

debug_workspace:
  stage: debug
  script:
    - pwd
    - ls -la
    - echo "Checking $APP_DIR"
    - test -f "$APP_DIR/Makefile" || (echo "FALTA $APP_DIR/Makefile" && exit 1)
    - find . -maxdepth 3 -type f -name pyproject.toml -o -name setup.cfg -o -name setup.py
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

lint_ruff:
  stage: lint
  before_script:
    - python --version
    - pip install --upgrade pip
    - apt-get update -y && apt-get install -y make
    - make -C "$APP_DIR" setup
  script:
    - make -C "$APP_DIR" lint           # ruff check src tests
  allow_failure: true
  artifacts:
    when: always
    paths:
      - $APP_DIR/.ruff_cache/
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

typecheck_mypy:
  stage: typecheck
  before_script:
    - python --version
    - pip install --upgrade pip
    - apt-get update -y && apt-get install -y make
    - make -C "$APP_DIR" setup
  script:
    - make -C "$APP_DIR" typecheck      # mypy src/toolkit
  allow_failure: true
  artifacts:
    when: always
    paths:
      - $APP_DIR/.mypy_cache/
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

tests_unit:
  stage: unit
  before_script:
    - python --version
    - pip install --upgrade pip
    - apt-get update -y && apt-get install -y make
    - make -C "$APP_DIR" setup
    - mkdir -p "$APP_DIR/reports"
  script:
    - make -C "$APP_DIR" test           # pytest (usa PYTEST_ADDOPTS)
  artifacts:
    when: always
    reports:
      junit: $APP_DIR/reports/junit.xml
    paths:
      - $APP_DIR/reports/
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_BRANCH == "main"

coverage_report:
  stage: coverage
  before_script:
    - python --version
    - pip install --upgrade pip
    - apt-get update -y && apt-get install -y make
    - make -C "$APP_DIR" setup
    - mkdir -p "$APP_DIR/reports"
  script:
    - make -C "$APP_DIR" test           # genera coverage.xml y htmlcov/ por PYTEST_ADDOPTS
  artifacts:
    when: always
    paths:
      - $APP_DIR/htmlcov/
      - $APP_DIR/reports/coverage.xml
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

analyze_toolkit:
  stage: analyze
  before_script:
    - python --version
    - pip install --upgrade pip
    - apt-get update -y && apt-get install -y make
    - make -C "$APP_DIR" setup
  script:
    - make -C "$APP_DIR" report         # genera report.json en la subcarpeta
  artifacts:
    when: always
    paths:
      - $APP_DIR/report.json
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
