"""Contracts and validation helpers for plugin reports."""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Literal, Protocol, TypedDict

# The impact level of the issue identified
Severity = Literal["info", "low", "medium", "high"]

"""
This class definition describes 'PluginMetadata' as a specialized dictionary type using TypedDict from the typing module.
It imposes that any dictionary treated as PluginMetadata must contain these three keys,
all mapped to string values:
- name: The unique, human-readable identifier for the plugin (e.g., "StyleChecker").
- version: The version number of the plugin (e.g., "1.2.0").
- description: A brief explanation of what the plugin does.
"""


class PluginMetadata(TypedDict):
    name: str
    version: str
    description: str


"""
This class definition describes the required and optional fields for a single issue report generated by a plugin,
using a special TypedDict structure. Note that most fields are marked as optional (total=False).

The (optional) fields are as follows:
- severity:	The impact level of the issue (e.g., "high," "low").
- code:	A unique, short identifier for the rule that was violated (e.g., "MAX_LINE_LENGTH").
- message:	A descriptive explanation of the issue (e.g., "Line is 90 chars, exceeds limit of 88").
- line:	The line number where the issue was found.
- col:	The column number where the issue begins (useful for exact positioning).
- hint:	Optional supplementary advice or a suggested fix for the issue.

BEWARE: the validation function (validate_plugin_report) dictates the actual required (non-optional)
runtime keys (like severity, code, and message), ensuring the minimal necessary information is
always present in the final report structure.
"""


class IssueResult(TypedDict, total=False):
    severity: Severity
    code: str
    message: str
    line: int
    col: int
    hint: str


"""
This class definition describes the required structure for the summary section of any plugin's analysis report,
ensuring consistent data types for two critical fields: the issues count and the execution status.

It defines 'PluginSummary' as a type hint using TypedDict from the typing module. This creates a
formal specification that any dictionary used to summarize a plugin's run MUST match.
"""


class PluginSummary(TypedDict):
    issues_found: int
    status: Literal["completed", "partial", "failed"]


"""
This class definition describes the precise structure for the data generated when a specific plugin
runs on a single file, using Python's static typing feature, TypedDict. It acts as the container that
holds both the detailed findings (results) and the execution metadata (summary) for a single plugin run.

All three fields are mandatory:
- plugin:   The unique name of the plugin that generated this report (e.g., "StyleChecker"). This identifies
            which analysis tool produced the results.
- results:  A list containing all the individual issues found by the plugin in the file. Each item in this list
            must conform to the IssueResult TypedDict structure.
- summary:  A dictionary containing the overall statistics for this plugin's run on the file.
            This must conform to the PluginSummary TypedDict structure.
"""


class PluginExecutionResult(TypedDict):
    plugin: str
    results: list[IssueResult]
    summary: PluginSummary


"""
This class definition describes the structured data format used to report all analysis findings for a single file
within the Code Quality Toolkit, utilizing the TypedDict feature for type enforcement.

-file:      The path (as a string) to the file that was analyzed. This is the primary identifier for the report.
-plugins:   A list containing the results from every plugin that ran on this specific file.
            Each item in this list must conform to the PluginExecutionResult TypedDict structure.
"""


class FileReport(TypedDict):
    file: str
    plugins: list[PluginExecutionResult]


"""
This class definition describes the required structure for the main statistical summary section of the final report.

All five fields are mandatory:
- total_files: The total number of files that were successfully scanned by the analysis engine.
- total_issues: The grand total of all issues found across all files and all plugins.
- issues_by_severity: A dictionary mapping each defined severity level to the total count of issues found at that level.
- issues_by_plugin: A dictionary mapping each plugin name to the total number of issues that plugin found.
- top_offenders: a list or modules with the highest concentration of issues.
"""


class UnifiedSummary(TypedDict):
    total_files: int
    total_issues: int
    issues_by_severity: dict[Severity, int]
    issues_by_plugin: dict[str, int]
    top_offenders: list[dict[str, int | str]]


"""
This class definition describes the required structure for the metadata section of the final analysis report.
It provides contextual information about when and how the analysis was executed.

This section serves as the header information for the final report. It ensures that the report is self-describing,
providing the necessary context (version and execution time) to interpret the results and verify the
integrity of the analysis run.

All four fields are mandatory:
- timestamp: The date and time when the analysis was run formatted as an ISO 8601 string (e.g., UTC).
- tool_version: The version number of the Code Quality Toolkit application itself.
- plugins_executed: A list containing the names of all plugins that were configured to run during the analysis.
- status: The overall execution status of the entire analysis engine, from the statuses of all individual plugins.
"""


class UnifiedMetadata(TypedDict):
    timestamp: str
    tool_version: str
    plugins_executed: list[str]
    status: Literal["completed", "partial", "failed"]


"""
This class definition describes the complete, top-level structure for the final output of the Code Quality Toolkit.
It represents the final dictionary that the analysis engine outputs (likely serialized to JSON)
after all files have been scanned, plugins run, and data aggregated.

This structure is the top-level container, bringing together the three major sections of the final report:
- metadata: A dictionary containing contextual information about the run itself, such as the timestamp,
            the tool version, and the overall execution status.
- summary:  A dictionary containing all the aggregated statistics, including total files, total issues,
            and breakdowns by plugin and severity. 
- details:  A list containing the complete, detailed analysis for every single file scanned.
            Each item in this list includes the file path and all issues reported by all plugins for that file.
"""


class UnifiedReport(TypedDict):
    analysis_metadata: UnifiedMetadata
    summary: UnifiedSummary
    details: list[FileReport]


class PluginProtocol(Protocol):
    """== Protocol that each and every plugin must implement ==

    This base class is used for structural subtyping (or Duck Typing) in Python.
    It means that any class defined elsewhere is considered a valid implementation of PluginProtoco if it
    structurally matches the methods defined here, regardless of whether it explicitly inherits from PluginProtocol.

    It acts as documentation and, more importantly, allows static type checkers (like Mypy) to verify
    that the main analysis engine only uses plugin objects that are guaranteed to have the necessary methods.
    """

    def get_metadata(self) -> PluginMetadata:
        """Return metadata about the plugin."""

    def analyze(self, source_code: str, file_path: str | None) -> dict[str, Any]:
        """Analyze the provided source code and return a plugin report."""


"""
This utility function performs a validation check to ensure that a given dictionary contains all the expected keys.
It helps ensuring data integrity before processing configuration files or report outputs.
"""


def _require_keys(data: dict[str, Any], keys: Iterable[str], context: str) -> None:
    for key in keys:
        if key not in data:
            raise ValueError(f"Missing key '{key}' in {context}")


def validate_plugin_report(data: dict[str, Any]) -> None:
    """== Validate the structure of a plugin report ==

    This function serves as a structural validator for the output generated by a code analysis plugin.
    It ensures that the report adheres to a strict, predefined format, preventing subsequent parts of the toolkit
    (like the aggregation engine) from crashing due to unexpected or malformed data.

    The function performs checks at three hierarchical levels:
    -> the top-level report, the summary dictionary, and each individual issue result.

    If all the checks pass, the function successfully returns None, indicating the plugin report
    is structurally sound and ready for aggregation.

    """

    # use helper function to check whether any essential keys are missing.
    _require_keys(data, ["results", "summary"], "plugin report")

    # checks whether results and summary are respectively a list and a dictionary
    results = data["results"]
    summary = data["summary"]
    if not isinstance(results, list):
        raise TypeError("'results' must be a list")
    if not isinstance(summary, dict):
        raise TypeError("'summary' must be a dict")

    # Ensure the summary statistics are correct and consistent:
    # 1) "status" must be one of the three valid strings: "completed", "partial", or "failed".
    _require_keys(summary, ["issues_found", "status"], "plugin summary")
    if summary["status"] not in {"completed", "partial", "failed"}:
        raise ValueError("Invalid plugin summary status")

    # 2) "issues_found" must be a non-negative integer (i.e., ≥0).
    issues_found = summary["issues_found"]
    if not isinstance(issues_found, int) or issues_found < 0:
        raise ValueError("'issues_found' must be a non-negative integer")

    # Iterates through every item in the results list to validate the structure of each reported issue
    for result in results:
        # 1) ensures every item in the results list is a dictionary
        if not isinstance(result, dict):
            raise TypeError("Each result must be a dict")

        # 2) Each issue dictionary must contain its three core fields for a meaningful report
        _require_keys(result, ["severity", "code", "message"], "issue result")

        # 3) the value for "severity" must be one of the four valid levels
        if result["severity"] not in {"info", "low", "medium", "high"}:
            raise ValueError("Invalid severity level")


def validate_unified_report(data: dict[str, Any]) -> None:
    """Validate the unified report schema."""

    _require_keys(data, ["analysis_metadata", "summary", "details"], "unified report")

    metadata = data["analysis_metadata"]
    summary = data["summary"]
    details = data["details"]

    if not isinstance(metadata, dict):
        raise TypeError("'analysis_metadata' must be a dict")
    _require_keys(
        metadata,
        ["timestamp", "tool_version", "plugins_executed", "status"],
        "metadata",
    )

    if metadata["status"] not in {"completed", "partial", "failed"}:
        raise ValueError("Invalid analysis status")

    if not isinstance(summary, dict):
        raise TypeError("'summary' must be a dict")
    _require_keys(
        summary,
        [
            "total_files",
            "total_issues",
            "issues_by_severity",
            "issues_by_plugin",
            "top_offenders",
        ],
        "summary",
    )

    if not isinstance(details, list):
        raise TypeError("'details' must be a list")

    if not isinstance(summary["issues_by_severity"], dict):
        raise TypeError("'issues_by_severity' must be a dict")
    for key in ["info", "low", "medium", "high"]:
        if key not in summary["issues_by_severity"]:
            raise ValueError("Missing severity key in summary")

    for file_entry in details:
        if not isinstance(file_entry, dict):
            raise TypeError("Each detail entry must be a dict")
        _require_keys(file_entry, ["file", "plugins"], "file entry")
        for plugin_entry in file_entry["plugins"]:
            if not isinstance(plugin_entry, dict):
                raise TypeError("Plugin entry must be a dict")
            _require_keys(
                plugin_entry, ["plugin", "results", "summary"], "plugin entry"
            )
            validate_plugin_report(plugin_entry)
